import type { Programme, Region } from './match';

/**
 * Regions whose own operational programme has actually been swept.
 *
 * Declared by hand, never derived from PROGRAMMES: a region with no entries
 * could mean "researched, nothing fits" or "never researched", and a funding
 * page must not let those two read the same. Anything outside this list sees
 * national instruments plus a notice saying its regional calls are not covered.
 *
 * Add a region here in the same change that adds its programmes, not before.
 */
export const COVERED_REGIONS: readonly Region[] = ['alentejo'];

// Facts only. Reader-facing copy lives in i18n/funding.ts. Every date and URL is
// source-checked by match.check.ts so an expired aviso cannot quietly read open.
export const PROGRAMMES: Programme[] = [
  {
    id: 'mpr-2026-6',
    code: 'MPr-2026-6',
    entity: 'Compete 2030',
    instrument: 'grant',
    regions: ['norte', 'centro', 'lisboa', 'alentejo', 'algarve'],
    purposes: ['digital', 'equipment', 'international'],
    amount: { min: 300_000, max: 25_000_000 },
    window: { kind: 'window', opens: '2026-06-15', closes: '2026-09-30' },
    applyUrl: 'https://www.digitalfundos.pt/balcao',
    sourceUrl: 'https://compete2030.gov.pt/wp-content/uploads/2026/06/Aviso-MPR_2026_6-InovacaoProdutiva_geral-v.-republicacao_27.08.2026.pdf',
    checkedOn: '2026-09-14',
    gates: [
      { kind: 'sizeIn', id: 'pme', sizes: ['micro', 'small', 'medium'] },
      { kind: 'filedAccounts', id: 'needsIes' },
      { kind: 'manual', id: 'innovativeTradableProject' },
    ],
  },
  {
    id: 'mpr-2026-7',
    code: 'MPr-2026-7',
    entity: 'Compete 2030',
    instrument: 'grant',
    regions: ['norte', 'centro', 'lisboa', 'alentejo', 'algarve'],
    purposes: ['rnd'],
    amount: { min: 200_000 },
    window: { kind: 'window', opens: '2026-07-14', closes: '2026-12-29' },
    applyUrl: 'https://www.digitalfundos.pt/balcao',
    sourceUrl: 'https://compete2030.gov.pt/wp-content/uploads/2026/07/MPR-2026-7_SIID-Demonstradores-Individuais-e-Copromocao_18-agosto26_republicacao.pdf',
    checkedOn: '2026-09-14',
    gates: [
      { kind: 'sizeIn', id: 'pme', sizes: ['micro', 'small', 'medium'] },
      { kind: 'filedAccounts', id: 'needsIes' },
      { kind: 'manual', id: 'demonstratorProject' },
    ],
  },
  {
    id: 'alt2030-2026-16',
    code: 'ALT2030-2026-16',
    entity: 'Alentejo 2030',
    instrument: 'grant',
    regions: ['alentejo'],
    regional: true,
    purposes: ['digital', 'equipment'],
    amount: { min: 15_000, max: 300_000 },
    rate: 0.6,
    window: { kind: 'window', opens: '2026-03-27', closes: '2026-09-01' },
    applyUrl: 'https://balcaofundosue.pt/',
    sourceUrl: 'https://acips.pt/wp-content/uploads/2026/04/ALT2030-2026-16.pdf',
    checkedOn: '2026-09-14',
    gates: [
      { kind: 'region', id: 'alentejo', regions: ['alentejo'] },
      { kind: 'caeIn', id: 'eligibleCae', prefixes: ['46', '47', '56', '62', '71', '75', '81', '86', '88', '93130', '95', '96'] },
      { kind: 'sizeIn', id: 'microOrSmall', sizes: ['micro', 'small'] },
      { kind: 'filedAccounts', id: 'needsIes' },
    ],
  },
  {
    id: 'alt2030-2025-25',
    code: 'ALT2030-2025-25',
    entity: 'Alentejo 2030',
    instrument: 'grant',
    regions: ['alentejo'],
    regional: true,
    purposes: ['digital', 'rnd', 'equipment'],
    amount: { max: 1_000_000 },
    rate: 0.75,
    window: { kind: 'window', opens: '2025-09-29', closes: '2026-03-31', nextExpected: '2026-09' },
    applyUrl: 'https://balcaofundosue.pt/',
    sourceUrl: 'https://alentejo.portugal2030.pt/2025/09/29/alentejo-2030-lanca-novos-avisos-de-apoio-ao-empreendedorismo-qualificado-e-a-qualificacao-das-empresas-num-investimento-global-de-25-milhoes-de-euros/',
    checkedOn: '2026-09-14',
    gates: [
      { kind: 'region', id: 'alentejo', regions: ['alentejo'] },
      { kind: 'sizeIn', id: 'microOrSmall', sizes: ['micro', 'small'] },
      { kind: 'maxAge', id: 'startupAge', years: 3 },
      { kind: 'manual', id: 'knowledgeIntensiveProject' },
    ],
  },
  {
    id: 'vale-digitalizacao',
    entity: 'IAPMEI',
    instrument: 'voucher',
    regions: 'all',
    purposes: ['digital'],
    amount: { min: 5_000, max: 20_000 },
    rate: 0.75,
    window: { kind: 'window', opens: '2026-01-15', closes: '2026-12-31' },
    applyUrl: 'https://balcaofundosue.pt/',
    sourceUrl: 'https://pmeincentivos.pt/incentivos/vale-digitalizacao-2026',
    checkedOn: '2026-09-14',
    gates: [{ kind: 'manual', id: 'confirmAvisoEligibility' }],
  },
  {
    id: 'iefp-mais-emprego',
    entity: 'IEFP',
    instrument: 'grant',
    regions: 'all',
    purposes: ['hiring'],
    amount: { min: 6_445, max: 15_469 },
    window: { kind: 'window', opens: '2026-07-15', closes: '2026-12-15' },
    applyUrl: 'https://iefponline.iefp.pt/IEFP/medida/mais-emprego.do',
    sourceUrl: 'https://www.iefp.pt/en/apoios-a-contratacao',
    checkedOn: '2026-09-14',
    gates: [{ kind: 'manual', id: 'iefpHireConditions' }],
  },
  {
    id: 'iefp-emprego-mais-talento',
    entity: 'IEFP',
    instrument: 'grant',
    regions: 'all',
    purposes: ['hiring'],
    window: { kind: 'window', opens: '2026-07-15', closes: '2026-12-15' },
    applyUrl: 'https://iefponline.iefp.pt/IEFP/medida/emprego-mais-talento.do',
    sourceUrl: 'https://iefponline.iefp.pt/IEFP/medida/emprego-mais-talento.do?action=overview',
    checkedOn: '2026-09-14',
    gates: [{ kind: 'manual', id: 'iefpTalentConditions' }],
  },
  {
    id: 'sifide-ii',
    entity: 'ANI',
    instrument: 'taxCredit',
    regions: 'all',
    purposes: ['rnd'],
    rate: 0.325,
    window: { kind: 'annual', month: 5 },
    applyUrl: 'https://www.gov.pt/servicos/submeter-a-candidatura-ao-sistema-de-incentivos-fiscais-a-i-d-empresarial-sifide-',
    sourceUrl: 'https://www.gov.pt/servicos/submeter-a-candidatura-ao-sistema-de-incentivos-fiscais-a-i-d-empresarial-sifide-',
    checkedOn: '2026-09-14',
    gates: [{ kind: 'manual', id: 'genuineRnd' }],
  },
  {
    id: 'bpf-investeu-pme',
    entity: 'Banco Português de Fomento',
    instrument: 'loan',
    regions: 'all',
    purposes: ['workingCapital', 'equipment', 'energy'],
    amount: { max: 8_250_000 },
    window: { kind: 'rolling' },
    applyUrl: 'https://www.bpfomento.pt/pt/catalogo/linha-de-garantia-bpf-investeu-pme-e-small-mid-caps/',
    sourceUrl: 'https://www.bpfomento.pt/pt/catalogo/linha-de-garantia-bpf-investeu-pme-e-small-mid-caps/',
    checkedOn: '2026-09-14',
    gates: [{ kind: 'manual', id: 'bankAppraisal' }],
  },
  {
    id: 'fomento-pt2030-garantias',
    entity: 'Banco Português de Fomento',
    instrument: 'guarantee',
    regions: 'all',
    purposes: ['digital', 'rnd', 'equipment', 'international', 'energy'],
    rate: 0.25,
    window: { kind: 'rolling' },
    applyUrl: 'https://www.bpfomento.pt/',
    sourceUrl: 'https://www.incentiva.pt/artigos/banco-de-fomento-linhas-credito-empresas-2026.html',
    checkedOn: '2026-09-14',
    gates: [{ kind: 'manual', id: 'approvedPortugal2030Project' }],
  },
  {
    id: 'rfai',
    entity: 'Autoridade Tributária',
    instrument: 'taxBenefit',
    regions: 'all',
    purposes: ['equipment'],
    window: { kind: 'annual', month: 5 },
    applyUrl: 'https://info.portaldasfinancas.gov.pt/',
    sourceUrl: 'https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/legislacao/diplomas_legislativos/Documents/Portaria_282_2014.pdf',
    checkedOn: '2026-09-14',
    gates: [{ kind: 'caeIn', id: 'eligibleCae', prefixes: ['05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '55', '56', '58', '591', '62', '631', '72', '77210', '90040', '91041', '91042', '93110', '93210', '93292', '93293', '96040', '82110', '82910'] }],
  },
];
