// Post-build. Writes a real index.html at every route path, plus the sitemap.
//
// GitHub Pages cannot set a status code, so an SPA route that only exists in
// the client router is served as 404.html — the reader sees the right page, but
// the response says 404 and search engines drop it. That was survivable when
// "/" was the only indexed URL; it is not now that every page is in the
// sitemap. A file on disk at /pt/quem-somos/index.html answers 200.
//
// 404.html stays as the fallback for genuinely unknown URLs, which is what
// makes LEGACY_ROUTES work.
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROUTES, LANGS, href, type RouteKey } from '../src/routes';
import en from '../src/i18n/en';
import pt from '../src/i18n/pt';

// cwd, not import.meta.url: esbuild bundles this into node_modules/.tmp, so the
// module's own path is not where the project is. pnpm runs scripts from the
// package root.
const dist = join(process.cwd(), 'dist');
const ORIGIN = 'https://nieusync.com';

// Params come from the dictionaries rather than a second hardcoded list, so a
// new pillar or legal document appears here the moment it is written.
const dicts = { pt, en };
const params: Partial<Record<RouteKey, (lang: 'pt' | 'en') => string[]>> = {
  pillars: (l) => dicts[l].site.pillars.items.map((p) => p.slug),
  legal: (l) => dicts[l].legal.docs.map((d) => d.slug),
};

// `pillars` only exists with a slug — there is no /pt/pilares index page, and
// emitting one would answer 200 and then redirect, which reads as a soft 404.
// `legal` does have an index (LegalIndex), so it is not in here.
const PARAM_ONLY: RouteKey[] = ['pillars'];

/** Every real URL on the site, grouped so a page and its translation stay paired. */
function allPaths(): Array<Record<'pt' | 'en', string>> {
  const out: Array<Record<'pt' | 'en', string>> = [];
  for (const key of Object.keys(ROUTES) as RouteKey[]) {
    if (!PARAM_ONLY.includes(key)) {
      out.push({ pt: href('pt', key), en: href('en', key) });
    }
    const slugs = params[key];
    if (!slugs) continue;
    // Slugs are identical across dictionaries by design (see routes.ts), so
    // pairing by index is safe — and check:i18n already fails if the two
    // dictionaries ever disagree on length.
    slugs('pt').forEach((slug, i) => {
      out.push({ pt: href('pt', key, slug), en: href('en', key, slugs('en')[i]) });
    });
  }
  return out;
}

const paths = allPaths();
const shell = readFileSync(join(dist, 'index.html'), 'utf8');

for (const pair of paths) {
  for (const lang of LANGS) {
    const path = pair[lang];
    if (path === `/${lang}`) {
      mkdirSync(join(dist, lang), { recursive: true });
      writeFileSync(join(dist, lang, 'index.html'), shell);
      continue;
    }
    const dir = join(dist, path);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'index.html'), shell);
  }
}

const priority = (path: string) =>
  /^\/(pt|en)$/.test(path) ? '1.0' : path.includes('/legal/') ? '0.3' : path.includes('/pilares/') || path.includes('/pillars/') ? '0.7' : '0.8';

const urls = paths
  .flatMap((pair) =>
    LANGS.map((lang) => {
      const alts = [
        `<xhtml:link rel="alternate" hreflang="pt-PT" href="${ORIGIN}${pair.pt}"/>`,
        `<xhtml:link rel="alternate" hreflang="en" href="${ORIGIN}${pair.en}"/>`,
        `<xhtml:link rel="alternate" hreflang="x-default" href="${ORIGIN}${pair.pt}"/>`,
      ];
      return `  <url>
    <loc>${ORIGIN}${pair[lang]}</loc>
    <priority>${priority(pair[lang])}</priority>
    ${alts.join('\n    ')}
  </url>`;
    }),
  )
  .join('\n');

writeFileSync(
  join(dist, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-static.ts from routes.ts and the i18n dictionaries.
     Do not edit: it is rewritten on every build. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urls}
</urlset>
`,
);

console.log(`✓ ${paths.length * LANGS.length} static paths + sitemap`);
